import localFont from "next/font/local";
import "./globals.css";
import ClientProvider from './ClientProvider';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={geistSans.className}>
        <ClientProvider>
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}